### ISSUE TITLE
Please publish

### ISSUE THREAD

**Issue by JohnMcLear** [bit/ep_webrtc#15]
this is broken...  Please give me access to publish

**Comment by bit** [comment]
0.0.6  was published 24 days ago https://www.npmjs.com/package/ep_webrtc to work with the current release. can also give you access to publish, how does that work?

**Comment by JohnMcLear** [comment]
I think you just ``npm owner add johnyma22 ep_webrtc``
https://docs.npmjs.com/cli/owner

**Comment by bit** [comment]
ok done
