### ISSUE TITLE
activation of audio/video chat

### ISSUE THREAD

**Issue by jindrichbartek** [bit/ep_webrtc#16]
Hi, am I missing something:
![v-etherpad](https://cloud.githubusercontent.com/assets/1358294/8678140/326fc1e2-2a53-11e5-8041-d447c2c89779.png)

How can I activate the audio or video chat? (From https://v.etherpad.org/p/ghcBFI8wmB)

**Comment by JohnMcLear** [comment]
Doh, try now.

**Comment by jindrichbartek** [comment]
Yep, super, now it works :-)
